services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252"
    depends_on:
      - proxy

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000"
    depends_on:
      - proxy

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"